/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppLayoutRouteImport } from './routes/app/_layout'
import { Route as AppLayoutQueriesRouteImport } from './routes/app/_layout/queries'
import { Route as AppLayoutGraphRouteImport } from './routes/app/_layout/graph'
import { Route as AppLayoutCorpusRouteImport } from './routes/app/_layout/corpus'
import { Route as AppLayoutChatRouteImport } from './routes/app/_layout/chat'
import { Route as AppLayoutQueriesQueryIdRouteImport } from './routes/app/_layout/queries.$queryId'
import { Route as AppLayoutCorpusPaperIdRouteImport } from './routes/app/_layout/corpus.$paperId'
import { Route as AppLayoutChatChatIdRouteImport } from './routes/app/_layout/chat.$chatId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AppRoute,
} as any)
const AppLayoutQueriesRoute = AppLayoutQueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutGraphRoute = AppLayoutGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutCorpusRoute = AppLayoutCorpusRouteImport.update({
  id: '/corpus',
  path: '/corpus',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutChatRoute = AppLayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutQueriesQueryIdRoute = AppLayoutQueriesQueryIdRouteImport.update({
  id: '/$queryId',
  path: '/$queryId',
  getParentRoute: () => AppLayoutQueriesRoute,
} as any)
const AppLayoutCorpusPaperIdRoute = AppLayoutCorpusPaperIdRouteImport.update({
  id: '/$paperId',
  path: '/$paperId',
  getParentRoute: () => AppLayoutCorpusRoute,
} as any)
const AppLayoutChatChatIdRoute = AppLayoutChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AppLayoutChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteWithChildren
  '/app/chat': typeof AppLayoutChatRouteWithChildren
  '/app/corpus': typeof AppLayoutCorpusRouteWithChildren
  '/app/graph': typeof AppLayoutGraphRoute
  '/app/queries': typeof AppLayoutQueriesRouteWithChildren
  '/app/chat/$chatId': typeof AppLayoutChatChatIdRoute
  '/app/corpus/$paperId': typeof AppLayoutCorpusPaperIdRoute
  '/app/queries/$queryId': typeof AppLayoutQueriesQueryIdRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRouteWithChildren
  '/app/chat': typeof AppLayoutChatRouteWithChildren
  '/app/corpus': typeof AppLayoutCorpusRouteWithChildren
  '/app/graph': typeof AppLayoutGraphRoute
  '/app/queries': typeof AppLayoutQueriesRouteWithChildren
  '/app/chat/$chatId': typeof AppLayoutChatChatIdRoute
  '/app/corpus/$paperId': typeof AppLayoutCorpusPaperIdRoute
  '/app/queries/$queryId': typeof AppLayoutQueriesQueryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteWithChildren
  '/app/_layout': typeof AppLayoutRouteWithChildren
  '/app/_layout/chat': typeof AppLayoutChatRouteWithChildren
  '/app/_layout/corpus': typeof AppLayoutCorpusRouteWithChildren
  '/app/_layout/graph': typeof AppLayoutGraphRoute
  '/app/_layout/queries': typeof AppLayoutQueriesRouteWithChildren
  '/app/_layout/chat/$chatId': typeof AppLayoutChatChatIdRoute
  '/app/_layout/corpus/$paperId': typeof AppLayoutCorpusPaperIdRoute
  '/app/_layout/queries/$queryId': typeof AppLayoutQueriesQueryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/app/chat'
    | '/app/corpus'
    | '/app/graph'
    | '/app/queries'
    | '/app/chat/$chatId'
    | '/app/corpus/$paperId'
    | '/app/queries/$queryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/app/chat'
    | '/app/corpus'
    | '/app/graph'
    | '/app/queries'
    | '/app/chat/$chatId'
    | '/app/corpus/$paperId'
    | '/app/queries/$queryId'
  id:
    | '__root__'
    | '/app'
    | '/app/_layout'
    | '/app/_layout/chat'
    | '/app/_layout/corpus'
    | '/app/_layout/graph'
    | '/app/_layout/queries'
    | '/app/_layout/chat/$chatId'
    | '/app/_layout/corpus/$paperId'
    | '/app/_layout/queries/$queryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_layout': {
      id: '/app/_layout'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_layout/queries': {
      id: '/app/_layout/queries'
      path: '/queries'
      fullPath: '/app/queries'
      preLoaderRoute: typeof AppLayoutQueriesRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/graph': {
      id: '/app/_layout/graph'
      path: '/graph'
      fullPath: '/app/graph'
      preLoaderRoute: typeof AppLayoutGraphRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/corpus': {
      id: '/app/_layout/corpus'
      path: '/corpus'
      fullPath: '/app/corpus'
      preLoaderRoute: typeof AppLayoutCorpusRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/chat': {
      id: '/app/_layout/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppLayoutChatRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/queries/$queryId': {
      id: '/app/_layout/queries/$queryId'
      path: '/$queryId'
      fullPath: '/app/queries/$queryId'
      preLoaderRoute: typeof AppLayoutQueriesQueryIdRouteImport
      parentRoute: typeof AppLayoutQueriesRoute
    }
    '/app/_layout/corpus/$paperId': {
      id: '/app/_layout/corpus/$paperId'
      path: '/$paperId'
      fullPath: '/app/corpus/$paperId'
      preLoaderRoute: typeof AppLayoutCorpusPaperIdRouteImport
      parentRoute: typeof AppLayoutCorpusRoute
    }
    '/app/_layout/chat/$chatId': {
      id: '/app/_layout/chat/$chatId'
      path: '/$chatId'
      fullPath: '/app/chat/$chatId'
      preLoaderRoute: typeof AppLayoutChatChatIdRouteImport
      parentRoute: typeof AppLayoutChatRoute
    }
  }
}

interface AppLayoutChatRouteChildren {
  AppLayoutChatChatIdRoute: typeof AppLayoutChatChatIdRoute
}

const AppLayoutChatRouteChildren: AppLayoutChatRouteChildren = {
  AppLayoutChatChatIdRoute: AppLayoutChatChatIdRoute,
}

const AppLayoutChatRouteWithChildren = AppLayoutChatRoute._addFileChildren(
  AppLayoutChatRouteChildren,
)

interface AppLayoutCorpusRouteChildren {
  AppLayoutCorpusPaperIdRoute: typeof AppLayoutCorpusPaperIdRoute
}

const AppLayoutCorpusRouteChildren: AppLayoutCorpusRouteChildren = {
  AppLayoutCorpusPaperIdRoute: AppLayoutCorpusPaperIdRoute,
}

const AppLayoutCorpusRouteWithChildren = AppLayoutCorpusRoute._addFileChildren(
  AppLayoutCorpusRouteChildren,
)

interface AppLayoutQueriesRouteChildren {
  AppLayoutQueriesQueryIdRoute: typeof AppLayoutQueriesQueryIdRoute
}

const AppLayoutQueriesRouteChildren: AppLayoutQueriesRouteChildren = {
  AppLayoutQueriesQueryIdRoute: AppLayoutQueriesQueryIdRoute,
}

const AppLayoutQueriesRouteWithChildren =
  AppLayoutQueriesRoute._addFileChildren(AppLayoutQueriesRouteChildren)

interface AppLayoutRouteChildren {
  AppLayoutChatRoute: typeof AppLayoutChatRouteWithChildren
  AppLayoutCorpusRoute: typeof AppLayoutCorpusRouteWithChildren
  AppLayoutGraphRoute: typeof AppLayoutGraphRoute
  AppLayoutQueriesRoute: typeof AppLayoutQueriesRouteWithChildren
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutChatRoute: AppLayoutChatRouteWithChildren,
  AppLayoutCorpusRoute: AppLayoutCorpusRouteWithChildren,
  AppLayoutGraphRoute: AppLayoutGraphRoute,
  AppLayoutQueriesRoute: AppLayoutQueriesRouteWithChildren,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AppRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
